# Generated by Django 3.2.6 on 2023-03-07 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('visit_count', models.IntegerField(default=0)),
                ('expire_time', models.IntegerField()),
                ('flow', models.IntegerField()),
                ('vote_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('create_time', models.IntegerField()),
                ('last_login_time', models.IntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('auth', models.IntegerField(default=1)),
                ('avator', models.TextField(default='22', max_length=10)),
                ('token', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VoteActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.IntegerField(unique=True)),
                ('flow', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('img', models.FileField(blank=True, upload_to='img', verbose_name='缩略图')),
                ('income', models.IntegerField(default=0)),
                ('create_time', models.IntegerField()),
                ('expire_time', models.IntegerField()),
                ('name', models.TextField(default='')),
                ('vote_everyday_begin_time', models.IntegerField(default=0)),
                ('vote_everyday_end_time', models.IntegerField(default=0)),
                ('vote_enroll_begin_time', models.IntegerField(default=0)),
                ('vote_enroll_end_time', models.IntegerField(default=0)),
                ('allowed_vote_region', models.TextField(default='')),
                ('visit_count', models.IntegerField(default=0)),
                ('visit_count_multiple', models.IntegerField(default=1)),
                ('vote_count_restrict', models.TextField(default='[]')),
                ('today_start_voteuser', models.IntegerField(default=0)),
                ('today_star_update_begin_time', models.IntegerField(default=0)),
                ('today_star_update_end_time', models.IntegerField(default=0)),
                ('allowed_alone_everyday_vote_count', models.IntegerField(default=0)),
                ('allowed_alone_everyhour_vote_count', models.IntegerField(default=0)),
                ('open_today_star_with', models.IntegerField(default=0)),
                ('visible_no1_with', models.IntegerField(default=0)),
                ('enable_vote_to_me', models.IntegerField(default=0)),
                ('enable_comment', models.IntegerField(default=0)),
                ('enable_vote_cert_code', models.IntegerField(default=0)),
                ('enable_prize', models.IntegerField(default=0)),
                ('enable_browser', models.IntegerField(default=0)),
                ('auto_comment_voteuser', models.IntegerField(default=0)),
                ('auto_comment_begin_time', models.IntegerField(default=0)),
                ('auto_comment_end_time', models.IntegerField(default=0)),
                ('auto_comment_everyday_begin_time', models.IntegerField(default=0)),
                ('auto_comment_everyday_end_time', models.IntegerField(default=0)),
                ('auto_comment_space_minute', models.IntegerField(default=0)),
                ('auto_comment_everyday_count_strict', models.IntegerField(default=0)),
                ('template_id', models.IntegerField(default=0)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.user', to_field='username')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.domain', to_field='domain_name')),
            ],
        ),
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=128, unique=True)),
                ('wx_username', models.TextField()),
                ('create_time', models.IntegerField()),
                ('avator', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='VoteTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='')),
                ('name', models.CharField(max_length=64)),
                ('count', models.IntegerField(default=0)),
                ('avator', models.FileField(blank=True, upload_to='img')),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteactivity', to_field='vote_id')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.IntegerField()),
                ('ip', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
                ('phone_model', models.TextField(default='')),
                ('system', models.TextField(default='')),
                ('network', models.TextField(default='')),
                ('vote_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteactivity', to_field='vote_id')),
                ('vote_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.votetarget')),
                ('voteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='vote_voteusers',
            field=models.ManyToManyField(through='main.VoteRecord', to='main.VoteUser'),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_time', models.IntegerField()),
                ('ip', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
                ('phone_model', models.TextField(default='')),
                ('system', models.TextField(default='')),
                ('network', models.TextField(default='')),
                ('prize_type', models.TextField(default='')),
                ('payment_order_id', models.TextField(default='')),
                ('payment_status', models.IntegerField(default=0)),
                ('vote_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteactivity', to_field='vote_id')),
                ('voteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.IntegerField()),
                ('voteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=11)),
                ('create_time', models.IntegerField()),
                ('status', models.IntegerField(default=False)),
                ('voteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
    ]
