# Generated by Django 3.2.6 on 2023-03-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230307_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterecord',
            name='phone_number',
        ),
    ]
