# Generated by Django 3.2.8 on 2023-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officialcount_name', models.TextField(default='')),
                ('region', models.TextField(default='')),
                ('wxpay_pos_id', models.TextField(default='')),
                ('wxpay_apiv2_secret_key', models.TextField(default='')),
                ('wxpay_apiv3_secret_key', models.TextField(default='')),
                ('qr_img', models.FileField(blank=True, upload_to='img/offcial_account_qr/', verbose_name='公众号二维码')),
                ('access_token_value', models.TextField(default='')),
                ('access_token_expire_time', models.IntegerField(default=0)),
                ('wxpay_mchid', models.TextField(default='')),
                ('wxpay_appid', models.TextField(default='')),
                ('wxpay_app_key', models.TextField(default='')),
                ('wxpay_notify_url', models.TextField(default='')),
            ],
        ),
    ]
