# Generated by Django 3.2.6 on 2023-02-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='vis_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
