# Generated by Django 3.2.6 on 2023-02-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('create_time', models.IntegerField()),
                ('last_login_time', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('auth', models.IntegerField(default=1)),
            ],
        ),
    ]
