# Generated by Django 3.2.6 on 2023-02-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_list', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('visit_count', models.IntegerField(default=0)),
                ('expire_time', models.IntegerField()),
                ('flow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=20)),
                ('action', models.TextField(max_length=20)),
                ('target', models.TextField(max_length=20)),
                ('create_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officialcount_name', models.TextField()),
                ('app_id', models.TextField()),
                ('region', models.TextField()),
                ('wxpay_pos_id', models.TextField()),
                ('wxpay_apiv2_secret_key', models.TextField()),
                ('wxpay_apiv3_secret_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32, unique=True)),
                ('expire_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('create_time', models.IntegerField()),
                ('last_login_time', models.IntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('auth', models.IntegerField(default=1)),
                ('avator', models.TextField(default='22', max_length=10)),
                ('token', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VoteActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.IntegerField(unique=True)),
                ('flow', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('img', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
                ('create_time', models.IntegerField()),
                ('expire_time', models.IntegerField()),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.user', to_field='username')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.domain', to_field='domain_name')),
            ],
        ),
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=128, unique=True)),
                ('wx_username', models.TextField()),
                ('create_time', models.IntegerField()),
                ('avator', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_username', models.TextField()),
                ('create_time', models.IntegerField()),
                ('vote_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteactivity', to_field='vote_id')),
                ('voteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_time', models.IntegerField()),
                ('ip', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
                ('system', models.TextField(default='')),
                ('network', models.TextField(default='')),
                ('vote_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteactivity', to_field='vote_id')),
                ('voteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.IntegerField()),
                ('voteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=11)),
                ('create_time', models.IntegerField()),
                ('status', models.IntegerField(default=False)),
                ('voteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
    ]
