# Generated by Django 3.2.6 on 2023-02-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
