# Generated by Django 3.2.6 on 2023-02-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
