# Generated by Django 3.2.6 on 2023-02-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_voteactivity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterecord',
            name='wx_username',
        ),
        migrations.AddField(
            model_name='voterecord',
            name='ip',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='network',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='system',
            field=models.TextField(default=''),
        ),
    ]
