# Generated by Django 3.2.6 on 2023-02-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.FileField(blank=True, null=True, upload_to='avator', verbose_name='头像'),
        ),
    ]
