# Generated by Django 3.2.6 on 2023-02-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230228_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_order_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='prize_type',
            field=models.TextField(default=''),
        ),
    ]
