# Generated by Django 3.2.6 on 2023-02-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230228_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='allowed_alone_everyday_vote_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='allowed_vote_region',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='visit_count_multiple',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='vote_enroll_begin_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='vote_enroll_end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='vote_everyday_begin_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='vote_everyday_end_time',
            field=models.IntegerField(default=0),
        ),
    ]
