# Generated by Django 3.2.6 on 2023-02-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230228_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='allowed_alone_everyhour_vote_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='enable_comment',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='enable_vote_cert_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='enable_vote_to_me',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='open_today_star_with',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='today_star_update_begin_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='today_star_update_end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='today_start_voteuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id'),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='visible_no1_with',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='vote_count_restrict',
            field=models.TextField(default=''),
        ),
    ]
