# Generated by Django 3.2.6 on 2023-02-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_avator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.IntegerField()),
                ('action', models.TextField(max_length=20)),
                ('target', models.TextField(max_length=20)),
                ('create_time', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.TextField(max_length=10),
        ),
    ]
