# Generated by Django 3.2.6 on 2023-02-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230228_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='auto_comment_begin_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='auto_comment_end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='auto_comment_everyday_begin_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='auto_comment_everyday_count_strict',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='auto_comment_everyday_end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='auto_comment_space_minute',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='auto_comment_voteuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_comment_voteuser', to='main.voteuser', to_field='open_id'),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='today_start_voteuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_start_voteuser', to='main.voteuser', to_field='open_id'),
        ),
    ]
