# Generated by Django 3.2.6 on 2023-02-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230224_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='who',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.TextField(default='22', max_length=10),
        ),
    ]
