# Generated by Django 3.2.6 on 2023-03-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230228_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteactivity',
            name='img',
            field=models.FileField(blank=True, upload_to='img', verbose_name='缩略图'),
        ),
    ]
