# Generated by Django 3.2.6 on 2023-03-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230301_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteactivity',
            name='allowed_alone_everyday_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='allowed_alone_everyhour_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='auto_comment_everyday_count_strict',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='auto_comment_space_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='enable_browser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='enable_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='enable_prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='enable_vote_cert_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='enable_vote_to_me',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='open_today_star_with',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='visible_no1_with',
            field=models.IntegerField(default=0),
        ),
    ]
