# Generated by Django 3.2.6 on 2023-02-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('app_id', models.TextField()),
                ('region', models.TextField()),
                ('wx_pay_pos_id', models.TextField()),
                ('wx_pay_apiv2_secret_key', models.TextField()),
                ('wx_pay_apiv3_secret_key', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
