# Generated by Django 3.2.6 on 2023-03-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230301_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='template_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='vote_count_restrict',
            field=models.TextField(default='[]'),
        ),
    ]
