# Generated by Django 3.2.6 on 2023-03-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230302_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='phone_model',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='phone_model',
            field=models.TextField(default=''),
        ),
    ]
