# Generated by Django 3.2.6 on 2023-02-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230227_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=128, unique=True)),
                ('wx_username', models.TextField()),
                ('create_time', models.IntegerField()),
            ],
        ),
    ]
