# Generated by Django 3.2.6 on 2023-03-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230302_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='vote_voteusers',
            field=models.ManyToManyField(through='main.VoteRecord', to='main.VoteUser'),
        ),
    ]
