# Generated by Django 3.2.6 on 2023-03-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_statics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statics',
            old_name='create_time',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='statics',
            name='now_month_income',
        ),
        migrations.RemoveField(
            model_name='statics',
            name='today_order_count',
        ),
        migrations.RemoveField(
            model_name='statics',
            name='yesterday_order_count',
        ),
    ]
