# Generated by Django 3.2.6 on 2023-03-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20230302_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_income', models.IntegerField(default=0)),
                ('day_time', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
            ],
        ),
    ]
