# Generated by Django 3.2.6 on 2023-03-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='status',
        ),
        migrations.AddField(
            model_name='settings',
            name='value',
            field=models.TextField(default=''),
        ),
    ]
