# Generated by Django 3.2.6 on 2023-03-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20230303_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='vote_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
