# Generated by Django 3.2.6 on 2023-03-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_votetarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteactivity',
            name='auto_comment_voteuser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='today_start_voteuser',
            field=models.IntegerField(default=0),
        ),
    ]
