# Generated by Django 3.2.6 on 2023-03-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_voterecord_vote_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voteuser',
            name='open_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
