# Generated by Django 3.2.6 on 2023-03-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20230307_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteactivity',
            name='vote_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
