# Generated by Django 3.2.6 on 2023-03-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_voteactivity_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='contact',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='enterprises',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='prize',
            field=models.TextField(default=''),
        ),
    ]
