# Generated by Django 3.2.6 on 2023-03-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20230307_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='support',
            field=models.TextField(default=''),
        ),
    ]
