# Generated by Django 3.2.6 on 2023-03-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_voteactivity_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(db_index=True, default='')),
                ('expire_time', models.IntegerField(default=0)),
                ('has_used', models.IntegerField(default=0)),
                ('user_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
    ]
