# Generated by Django 3.2.6 on 2023-03-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_keys_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyprize',
            name='vote_activity',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='applyprize',
            name='voteuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteuser', to='main.voteuser', to_field='open_id'),
        ),
    ]
