# Generated by Django 3.2.6 on 2023-03-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterecord',
            name='phone_number',
        ),
    ]
