# Generated by Django 3.2.8 on 2023-03-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20230308_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='top_roll_text',
            field=models.TextField(default=''),
        ),
    ]
