# Generated by Django 3.2.8 on 2023-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_voteactivity_top_roll_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='start_adv_img',
            field=models.FileField(blank=True, upload_to='img', verbose_name='开场广告图'),
        ),
    ]
