# Generated by Django 3.2.8 on 2023-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_voteactivity_start_adv_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='bottom_text',
            field=models.TextField(default=''),
        ),
    ]
