# Generated by Django 3.2.8 on 2023-03-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_voteactivity_video_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='bottom_support_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='target_video_adv',
            field=models.FileField(blank=True, upload_to='vedio', verbose_name='视频广告'),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='video_adv',
            field=models.FileField(blank=True, upload_to='video', verbose_name='视频广告'),
        ),
    ]
