# Generated by Django 3.2.8 on 2023-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20230308_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='carousel_list',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='temp_file',
            field=models.FileField(blank=True, upload_to='tmp', verbose_name='临时文件'),
        ),
    ]
