# Generated by Django 3.2.8 on 2023-03-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20230308_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='bottom_copyright',
            field=models.TextField(default=''),
        ),
    ]
