# Generated by Django 3.2.8 on 2023-03-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_voteactivity_bottom_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='officialcount_qrcode',
            field=models.FileField(blank=True, upload_to='pr', verbose_name='公众号二维码'),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='popup',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='CommentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('create_time', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('vote_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteactivity', to_field='vote_id')),
                ('vote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voteuser', to_field='open_id')),
            ],
        ),
    ]
