# Generated by Django 3.2.8 on 2023-03-09 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20230308_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentrecord',
            name='vote_activity',
        ),
        migrations.AddField(
            model_name='commentrecord',
            name='vote_target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.votetarget'),
            preserve_default=False,
        ),
    ]
