# Generated by Django 3.2.8 on 2023-03-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20230309_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentRecord',
        ),
    ]
