# Generated by Django 3.2.8 on 2023-03-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_commentrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentRecord',
        ),
    ]
