# Generated by Django 3.2.8 on 2023-03-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_commentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='vote_button_name',
            field=models.TextField(default='点赞'),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='vote_unit_name',
            field=models.TextField(default='个'),
        ),
    ]
