# Generated by Django 3.2.8 on 2023-03-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='vote_user',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='open_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='domain',
            field=models.TextField(default=''),
        ),
    ]
