# Generated by Django 3.2.8 on 2023-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20230309_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='temp', verbose_name='临时文件')),
            ],
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='temp_file',
            field=models.FileField(blank=True, upload_to='temp', verbose_name='临时文件'),
        ),
    ]
