# Generated by Django 3.2.8 on 2023-03-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20230309_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votetarget',
            name='avator',
            field=models.FileField(blank=True, default='img/1.png', null=True, upload_to='img'),
        ),
    ]
