# Generated by Django 3.2.8 on 2023-03-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_votetarget_avator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
