# Generated by Django 3.2.8 on 2023-03-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteactivity',
            name='auto_comment_voteuser',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='today_start_voteuser',
            field=models.CharField(default='', max_length=128),
        ),
    ]
