# Generated by Django 3.2.8 on 2023-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20230309_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='domain',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='ip',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='open_id',
            field=models.TextField(default='', null=True),
        ),
    ]
