# Generated by Django 3.2.8 on 2023-03-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20230309_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='img',
            field=models.FileField(blank=True, upload_to='img/gift', verbose_name='礼物图标'),
        ),
    ]
