# Generated by Django 3.2.8 on 2023-03-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_gift_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteactivity',
            name='officialcount_qrcode',
            field=models.FileField(blank=True, upload_to='qr', verbose_name='公众号二维码'),
        ),
    ]
