# Generated by Django 3.2.8 on 2023-03-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_voteactivity_officialcount_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactivity',
            name='track_report',
            field=models.TextField(default=''),
        ),
    ]
