# Generated by Django 3.2.8 on 2023-03-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_voteactivity_officialcount_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocomment',
            name='day_end_time',
            field=models.IntegerField(default=0),
        ),
    ]
