# Generated by Django 3.2.8 on 2023-03-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_autocomment_day_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialaccount',
            name='qr_img',
            field=models.FileField(blank=True, upload_to='img/offcial_account_qr/', verbose_name='公众号二维码'),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='carousel_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='voteactivity',
            name='template_id',
            field=models.IntegerField(default=1),
        ),
    ]
