# Generated by Django 3.2.8 on 2023-03-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20230311_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='votetarget',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
