# Generated by Django 3.2.8 on 2023-03-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_votetarget_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, default='null', max_length=6)),
                ('name', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('msg', models.TextField(default='')),
            ],
        ),
    ]
