# Generated by Django 3.2.8 on 2023-03-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_time',
            field=models.IntegerField(default=0),
        ),
    ]
