# Generated by Django 3.2.8 on 2023-03-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_task_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteactivity',
            name='vote_voteusers',
        ),
        migrations.AddField(
            model_name='votetarget',
            name='vote_voteusers',
            field=models.ManyToManyField(through='main.VoteRecord', to='main.VoteUser'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='img',
            field=models.FileField(blank=True, default='img/gift/rose.png', upload_to='img/gift', verbose_name='礼物图标'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vote_activity',
            field=models.IntegerField(default=0),
        ),
    ]
