# Generated by Django 3.2.8 on 2023-03-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20230312_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialaccount',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='votetarget',
            name='vote_voteusers',
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='access_token_advanced_expire_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='access_token_advanced_value',
            field=models.TextField(default='', verbose_name='高级accesstoken'),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='access_token_expire_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='access_token_value',
            field=models.TextField(default='', verbose_name='基础accesstoken'),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='wxpay_app_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='wxpay_appid',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='wxpay_mchid',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='wxpay_notify_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='officialaccount',
            name='officialcount_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='officialaccount',
            name='region',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='officialaccount',
            name='wxpay_apiv2_secret_key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='officialaccount',
            name='wxpay_apiv3_secret_key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='officialaccount',
            name='wxpay_pos_id',
            field=models.TextField(default=''),
        ),
    ]
