# Generated by Django 3.2.8 on 2023-03-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20230313_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
