# Generated by Django 3.2.8 on 2023-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_paymentrecord_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='support_count',
            field=models.IntegerField(default=1),
        ),
    ]
