# Generated by Django 3.2.8 on 2023-03-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20230313_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteactivity',
            name='track_report',
            field=models.TextField(default='[]'),
        ),
    ]
