# Generated by Django 3.2.8 on 2023-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_voteactivity_track_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteactivity',
            name='popup',
            field=models.TextField(default='[]'),
        ),
    ]
