# Generated by Django 3.2.8 on 2023-03-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_paymentrecord_vote_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='update_time',
            field=models.IntegerField(default=0),
        ),
    ]
