# Generated by Django 3.2.8 on 2023-03-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_paymentrecord_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterecord',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
