# Generated by Django 3.2.8 on 2023-03-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_voterecord_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_order_id',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
